### ISSUE TITLE
ffmpeg - Windows Requirements

### ISSUE THREAD

**Issue by CeterPushing** [cocktailpeanut/facefusion.pinokio#1]
note for Windows users, install ffmpeg manually and set system path first before installing this, there is no mechanism to do this within the installer.

**Comment by cocktailpeanut** [comment]
Which version of pinokio are you using?

The latest version of pinokio includes FFmpeg by default, which means you shouldn't have to do this from each installer, but should just work out of the box.

If you have the latest version but still have this issue, please report in Discord, will take a look.

**Comment by CeterPushing** [comment]
My apologies, I was using an older version, in fact it was a release from mid-July ;)
