### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by webmaster-exit-1** [cocktailpeanut/facefusion.pinokio#7]
All anything does when you click download is open a new window. Nothing works.

**Comment by maggenti** [comment]
I would not say it does nothing, but it will not install correctly, it seems to hang on the Cuda.json for some reason. It brings up the gradio interface, and nothing works at that point. I tried the update and let it run for several hours and still nothing works. Not understanding why it never seems to error out, just keeps grinding away.

**Comment by webmaster-exit-1** [comment]
yup
